### ISSUE TITLE
NPE in uploads sample when trying to delete uploaded file

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/refapp#16]
Platform version: 6.8+
Refapp

1. Open Tests -> Component samples -> Uploads
2. Click `Show clear button` to add clear button for the upload field
3. Upload some file
4. Try to clear

```
java.lang.NullPointerException
	at com.haulmont.refapp.gui.app.sample.valueinputcomponents.uploads.UploadSample.lambda$init$0(UploadSample.java:62)
	at com.haulmont.bali.events.EventRouter.fireEvent(EventRouter.java:45)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.lambda$attachListener$6f56ebaa$1(WebAbstractField.java:331)
	at sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1199)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:600)
	at com.vaadin.ui.AbstractField.setValueIgnoreReadOnly(AbstractField.java:479)
	at com.haulmont.cuba.web.gui.components.WebAbstractField.setValue(WebAbstractField.java:244)
	at com.haulmont.cuba.web.gui.components.WebFileUploadField.clearButtonClicked(WebFileUploadField.java:134)
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### QA

There was an issue in sample. Should be working now.

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[219eadcd](https://git.haulmont.com/platform/refapp/commit/219eadcd2f72bdfbceca9a4aa87712581ca01b35) in **release_6_8** - NPE in uploads sample when trying to delete uploaded file #16

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[dd36baa4](https://git.haulmont.com/platform/refapp/commit/dd36baa411b2412c54311a7ea8ded81292bf2442) in **release_6_9** - NPE in uploads sample when trying to delete uploaded file #16

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[1eef9902](https://git.haulmont.com/platform/refapp/commit/1eef990295b16700ed895e1b8899b0fdf37ee10f) in **release_6_10** - NPE in uploads sample when trying to delete uploaded file #16

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[96ce9d60](https://git.haulmont.com/platform/refapp/commit/96ce9d601bb49531aa4931ffb28d8d0ea4a7270c) in **release_7_0** - NPE in uploads sample when trying to delete uploaded file #16

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[a9cb97f2](https://git.haulmont.com/platform/refapp/commit/a9cb97f2aecf8146aeb41e0d3709317316197dbc) in **master** - NPE in uploads sample when trying to delete uploaded file #16
