### ISSUE TITLE
ClassCastException in Suggestion Field Sample

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/refapp#17]
1) Open the **Refapp**
2) Select **Tests** -> **Component samples** -> **Suggestion Field**

**AR**:

```ClassCastException: java.lang.Integer cannot be cast to java.lang.String```

Logs:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.haulmont.cuba.web.gui.components.WebTextField.convertToPresentation(WebTextField.java:140)
	at com.haulmont.cuba.web.gui.components.WebTextField.convertToPresentation(WebTextField.java:51)
	at com.haulmont.cuba.web.gui.components.WebAbstractValueComponent.setValue(WebAbstractValueComponent.java:95)
	at com.haulmont.refapp.gui.app.sample.valueinputcomponents.selects.suggestionfield.SuggestionFieldSample.initTextFields(SuggestionFieldSample.java:109)
	at com.haulmont.refapp.gui.app.sample.valueinputcomponents.selects.suggestionfield.SuggestionFieldSample.init(SuggestionFieldSample.java:46)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:98)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:127)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:56)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:229)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:1033)
	at com.haulmont.cuba.gui.components.HasWindowManager.openWindow(HasWindowManager.java:75)
	at com.haulmont.refapp.gui.app.sample.SamplesMenu.openSampleScreen(SamplesMenu.java:38)
```

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[c1d74f82](https://git.haulmont.com/platform/refapp/commit/c1d74f8259e88a0c8350593857f3ed019c2d9b55) in **release_7_0** - ClassCastException in Suggestion Field Sample #17

**Comment by haulmont-git** [comment]
Git changesets by `tsarev`: 

[32215c23](https://git.haulmont.com/platform/refapp/commit/32215c23b1236acb87bdd34131a8f45f815095c8) in **master** - ClassCastException in Suggestion Field Sample #17
